### ISSUE TITLE
Has Ceased to Function

### ISSUE THREAD

**Issue by PrettzL** [sersorrel/mute-tab#12]
See title. As of one of the recent updates to Chrome this extension no longer functions.

**Comment by keysmashes** [comment]
Hi! Sorry to hear about the trouble. Please could you send me a couple of details so I can try to fix the problem?

Firstly: what operating system are you using (e.g. Windows, macOS, Linux), and which version of Chrome do you have installed? You can find out the latter by browsing to chrome://version - feel free to just copy-paste that entire page into this issue if you'd like.

Secondly: when you say "no longer functions", presumably that means that clicking the Tab Muter icon doesn't mute the current tab any more. (If you've set up a keyboard shortcut and it's not working any more, check if Chrome's forgotten about the shortcut you set up; a couple of people have reported that happening to them.) Please could you visit the Tab Muter options page, check the "debug mode" checkbox, then click the Tab Muter icon a couple of times, as if you were trying to mute and unmute the tab, and send me the debug log it produces?

Lastly: if you install a different tab-muting extension, and use it to mute a tab, does the Tab Muter icon update to show whether the tab is muted or not, or not?

Thanks!

**Comment by PrettzL** [comment]
First:
Windows 10

<details><summary>Google Chrome	103.0.5060.134 (Official Build) (64-bit) (cohort: Stable) </summary>

Revision	8ec6fce403b3feb0869b0732eda8bd95011d333c-refs/branch-heads/5060@{#1262}
OS	Windows 10 Version 21H2 (Build 19044.1826)
JavaScript	V8 10.3.174.20
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Command Line	"C:\Program Files\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end
Executable Path	C:\Program Files\Google\Chrome\Application\chrome.exe
Profile Path	C:\Users\\\[scrubbed]\AppData\Local\Google\Chrome\User Data\Profile 5
Active Variations	52d268a5-ca7d8d80
c264dd48-ca7d8d80
4dc415b1-ca7d8d80
3e7d7783-ced64eb0
7e184ca7-33c3eba5
16b16054-377be55a
7f244f68-ca7d8d80
59b6f412-377be55a
60d4b352-377be55a
3e8fe123-ca7d8d80
f36987f-377be55a
13acb500-ca7d8d80
15e85316-ca7d8d80
4e1a642f-377be55a
fa43222c-12ede6a2
534138de-ca7d8d80
72233f8b-ca7d8d80
273268f8-7c85fa18
6cb5e962-377be55a
e9e64bcb-ca7d8d80
a77166f2-377be55a
9d165456-83c7a291
eddd0d82-7723ede9
653bb15c-377be55a
1b69a7e4-ca7d8d80
cae31965-1372936b
a7ecc4d1-377be55a
826f3281-ca7d8d80
d7f231f3-ca7d8d80
87f33ad6-377be55a
afb5d7b8-b3211f8e
3095aa95-3f4a17df
c27fec31-89226029
d6ad7f9a-ca7d8d80
b253fceb-8010d287
250dda8b-8924bcae
a6a93650-43f9f30d
1e940a7c-ca7d8d80
ef1cfe77-ca7d8d80
4749874c-3410fc71
3f6e921e-377be55a
b6678808-ca7d8d80
7f122175-1f8c5973
5c4d440e-ca7d8d80
4e3ec83a-ca7d8d80
42f1f10d-4665a9f8
440a1764-377be55a
53fd5552-da90b91f
2aed9870-65cc1313
a582a1b8-ad75ce17
8d569531-4f54ac4d
da2d8531-bc5c0615
7bb3eec2-ca7d8d80
fc72a64b-ca7d8d80
2ba47366-ca7d8d80
248c3fbd-ca7d8d80
f30c9422-ca7d8d80
c272f203-ca7d8d80
eb871034-ca7d8d80
a7d30c71-8c87d088
1dc2d1e1-377be55a
5a1be9da-ca7d8d80
fbb2e0d5-377be55a
5e3a236d-4113a79e
e79de56c-377be55a
357a64de-377be55a
f6ae0543-377be55a
a1e2fead-33c3eba5
2fb38473-b9985617
bdf0dac0-f4bec4a5
92f965e9-33c3eba5
7da718e5-dfb2c590
a79ba57a-3d47f4f4
2b4e7fda-225b12df
9a9bd697-ca7d8d80
9d40711-ca7d8d80
9ef40aad-ca7d8d80
7d66e042-43f9f30d
9529a854-ca7d8d80
815d8cdb-377be55a
da493d3c-ca7d8d80
64a3b934-61adb70b
e559a54e-377be55a
234de0a0-377be55a
b7a22696-12ede6a2
a284ff81-377be55a
1bb3666c-c3bcb004
60fdb59-377be55a
47de1263-3d47f4f4
4ea303a6-ecbb250e
4949c1d8-ca7d8d80
baee3c29-377be55a
15d3083e-ca7d8d80
2e0ef3d0-6ad34519
ae747655-377be55a
7aa46da5-c946b150
c9e4cf65-12ede6a2
31af02a2-ca7d8d80
29be5dec-237776d1
d990c4ac-ca7d8d80
a18444ea-12ede6a2
9909b8ac-ca7d8d80
9f7bb00b-ca7d8d80
d2593aa0-ca7d8d80
7760b5b2-ca7d8d80
caa76e48-c94f66c2
ad4acdda-ca7d8d80
494d8760-52325d43
f47ae82a-746c2ad4
7b2873c2-f013ce2
3ac60855-486e2a9c
f48c01d3-58edb386
63dcb6a3-7564fb06
e706e746-a89e47bc
f296190c-a5822863
4442aae2-75cb33fc
f690cf64-a90023b1
ed1d377-e1cc0f14
75f0f0a0-d7f6b13c
710c3f90-6bdfffe7
e2b18481-bd104136
e7e71889-4ad60575
6a24725f-ca7d8d80
3a8271ac-12c226
b1ceb06f-d1372334
c7e5450f-ca7d8d80
ae82076d-ca7d8d80
17aec314-ca7d8d80
7f3f5a7a-29765637
2d3dfd19-377be55a
96d16546-16ca73f0
f6e27768-ca7d8d80
595f5eb0-ca7d8d80
bef5c006-73607f75
a48e59bf-3f4a17df
17b84626-377be55a
58ca9651-377be55a
662773da-33c3eba5
20cf9c63-377be55a
89f843ca-aec2a938
c4c291c4-3f4a17df
d661ac70-ca7d8d80
759576b5-33c3eba5
def27776-ca7d8d80
2856aa31-269bb9a4
4da3fbb2-377be55a
</details>

Second part:
I haven't set up a keyboard shortcut, though I did attempt to do what you asked.

Checked the Debug mode checkbox and clicked the Tab Mute icon a couple times, I wasn't able to discern where it output a debug file though. Was unable to find any .log files in any directories within '/profile 5' that were generating with timestamps for the time I clicked the icon. Assist?

Any other particular tab-muter extensions you would suggest for doing that last bit? I'll get back to you with those results asap.

**Comment by keysmashes** [comment]
The way the debug logs work is a bit weird, sorry – after you check the "debug mode" checkbox, if you leave the options page open, the page should update once any logs are collected:

![image](https://user-images.githubusercontent.com/9433472/183401558-854e9d6d-78f6-457b-b13c-195094e2303d.png)

If that's not happening when you click the extension icon, that's useful to know. It might still collect some logs if you mute tabs with another extension, though, so if you could check for that, that would be ideal.

From a brief look, the [Mute Tab extension](https://chrome.google.com/webstore/detail/mute-tab/blljobffcekcbopmkgfhpcjmbfnelkfg) looks ok. I _think_ using the built-in Chrome feature should work too – right-click on a tab, and there should be a "Mute site" entry.

**Comment by PrettzL** [comment]
Alright, so it's for sure not updating with that button and the added text for debugging.

One change I did notice upon using 'Mute site' was this gets greyed out.
![chrome_PD10LqDgRH](https://user-images.githubusercontent.com/109771518/183476475-10f77846-0011-4d5f-809a-55dcc6fe5223.png)
![chrome_gi6iSZuwqW](https://user-images.githubusercontent.com/109771518/183476482-06e94a68-b3d8-4ed8-af20-008bb10929d6.png)
That is 'google cast', might be having an interaction?

Tested out the suggested extension 'Mute Tab' and it functions correctly but doesn't appear to create any response in 'Tab Muter' for Debug mode.

Hope that helps with identifying the issue.

Let me know if there's anything else I can do to assist.

**Comment by keysmashes** [comment]
Hmmmm. That's very useful, thanks; unfortunately I think we're getting close to the limits of what Chrome problems I can debug, but there are a few more things you could check that might be useful, if you have the time.

If you browse to chrome://extensions, you should see a "Developer mode" toggle in the top-right – if you enable that, you should see some extra text show up in the Tab Muter card. The ID should be `bnclejfcblondkjliiblkojdeloomadd` (and btw the Tab Muter version number should be 1.4.2, I should have checked that earlier), and there should be an "Inspect views background.html" link that should say "(inactive)" after it (if it doesn't, wait about 15 seconds and the "(inactive)" text should appear).

1. While it says "background.html (inactive)", if you click the Tab Muter mute/unmute icon, does the "(inactive)" text disappear? What about muting tabs with another extension, or via "mute site"? What about if you switch tabs, or open a new tab/window?
2. Click the "background.html" link, and a window called "DevTools" should pop up. Open the Console tab, paste this text into it, and press enter: `chrome.windows.onCreated.addListener(function () { console.log('window created'); });`
3. If you click the Tab Muter mute/unmute icon (or use the other extension or "mute site") with the DevTools Console open, you _should_ see some logs appear in the DevTools window that look like `icon clicked` or `toggle mute state` with a bunch of text after them (these are the logs that debug mode is meant to produce). You should at minimum see the text `window created` appear if you open a new Chrome window. Please could you copy-paste or screenshot any logs you see there and post them here, or let me know if there are no logs?
4. If at any point you notice a red "Errors" button on the Tab Muter card at chrome://extensions, please could you click it and take a screenshot of the list of errors that appears, then post that screenshot here?

Make sure you disable developer mode in chrome://extensions once you're done :)

I'm currently somewhat suspicious that this could be related to a bug in Chrome (crbug 1316588); those tests should tell us whether it's the same underlying problem or not.

**Comment by keysmashes** [comment]
One other thing I just remembered: if you head to chrome://extensions-internals, you should see a bunch of data about the extensions you have installed. Search for `bnclejfcblondkjliiblkojdeloomadd` with ctrl-f, and you'll find the section about Tab Muter.

It would be really useful if you could, once you've done the steps above, send me the text about Tab Muter from that page – the data about each extension is separated by a line containing just `}, {`, and I need everything between the two of those that includes the line `"id": "bnclejfcblondkjliiblkojdeloomadd",`; on my machine, the first line starts `"creation_flags":` and the last line starts `"version":`. Post it here if you'd like, or email it to cws-support@sorrel.sh or support@tab.muter.computer; it might contain your username, so you might rather not post it in public. (If you can't work out which bit's related to Tab Muter, feel free to just send the whole page to either of those email addresses; the full page shows which extensions you use, but I don't _think_ it includes any potentially-personal information other than that.)

**Comment by PrettzL** [comment]
I'm sorry for the delayed response!

So the extension has started working again over the last couple of days.

I'm not sure what I could have done/changed.

Are you still interested in collecting the information you asked for in the previous response?

**Comment by keysmashes** [comment]
No worries at all, glad it's started working again – sometimes computers are just like that... Don't worry about the stuff I mentioned above, no, if it's started working again then looking at those logs now won't help work out why it stopped working originally.

If it breaks in the same way in the future, then collecting some debugging information with the steps above would be helpful, though :) I'll close this issue now, but drop a comment here if the problem comes back and I'll reopen it.
