### ISSUE TITLE
Keyboard Shortcut?

### ISSUE THREAD

**Issue by pepanee** [sersorrel/mute-tab#13]
Is it possible to implement a feature to set a custom keyboard shortcut to enable the muting of a current tab? If not able to set a custom keyboard shortcut, can you implement a certain keyboard shortcut to disable the audio for a current tab please?
Thanks

**Comment by keysmashes** [comment]
Hi! If you head to chrome://extensions/shortcuts, you should be able to find Tab Muter in the list there and assign a keyboard shortcut to "activate the extension", which will toggle mute for the current tab. (Let me know if that doesn't work, though.)

**Comment by pepanee** [comment]
Okay yes! I've accessed this in the past and had a keyboard shortcut set for it. Apparently I forgot how to go to the shortcuts page in Chrome, and apparently Chrome removed a keyboard shortcut that I had set in the past. 
I got it working again! Thanks for your reply. I appreciate it =)
