### ISSUE TITLE
mute-broken v1.4.0 @ chrome 85.0

### ISSUE THREAD

**Issue by wadabum** [sersorrel/mute-tab#4]
Out of nowhere a muted tab unmuted itself,
and i cant mute any tabs anymore (using the extension)

-> enabling debug log shows nothing
-> chromeDevtools (for backgroundJs) show nothing
-> the core method, `chrome.tabs.update(tab.id, {"muted": !isMuted})` i verified to work fine still.

restarted browser and reinstalled extension without luck.

extension 1.4.0
chrome 85.0

**Comment by YuvalShor** [comment]
Can confirm I'm having the same issue.

**Comment by keysmashes** [comment]
Thanks for reporting, sorry about that – I've uploaded a fixed version for review, hopefully it gets published soon.

**Comment by keysmashes** [comment]
Version 1.4.1 is now published and rolling out to all users, with this issue fixed. You should receive the update automatically in the next day or so; if you need it sooner, you can force an update check manually:

- go to chrome://extensions
- turn on "developer mode" with the toggle in the top-right
- press the "update" button near the top of the screen
- check that the version number for Tab Muter is (at least) 1.4.1
- turn off developer mode (toggle in the top-right)

(it might take a couple of hours for the Chrome Web Store to make the update available to all users)

Again, sorry for the inconvenience!
