### ISSUE TITLE
mute-broken v1.4.1 chrome 75.0

### ISSUE THREAD

**Issue by RoundCat98** [sersorrel/mute-tab#6]
i cant mute any tabs anymore after 1.4.1 update

I do not know how to use the developer tools to check extensions
(upd: debugging background.html and devtools say 1 error "Uncaught SyntaxError: Unexpected token . debug.js:52" )

extension 1.4.1
chrome 75.0

**Comment by keysmashes** [comment]
Hiya! This should be fixed in the next update, but the cause is that your version of Chrome is very old (released over a year ago) – updating to a newer Chrome version would also fix the issue.
